### ISSUE TITLE
Add ability to check for and retrieve a value by TypeId

### ISSUE THREAD

**Issue by palodequeso** [chris-morgan/anymap#18]
I'm trying to write an entity component system for game development, and I've gotten to the point where I would like to start caching lists of components for a system, so my first thought was to have a component trait that returns a list of TypeIds which describes which component types are required. Then the idea is to iterate over them when it is time to update the list of components and retrieve the value of the AnyMap by the TypeId. Currently there doesn't seem to be a way to do that exposed in your library, but it doesn't look like it would be too hard, but I'm not confident in my Rust skills yet to make a pull request myself.

My request is for a set of methods like contains_typeid, get_by_typeid, etc...

**Comment by chris-morgan** [comment]
I’ve been contemplating the untyped access surface area for a few weeks—is it worthwhile having a `&Any`-yielding iterator, for example? This stuff falls into much the same category, allowing much lower-level access to the underlying map.

Another idea occurred to me which could handle most or all of these cases: simply adding a pair of methods for raw access to the underlying hash map.

- `fn as_raw(&self) -> &HashMap<TypeId, Box<Any>, TypeIdState>`, for “normal” use (the methods you described), and
- `fn into_raw(self) -> HashMap<TypeId, Box<Any>, TypeIdState>` largely just for consuming the whole thing (a `Box<Any>` iterator, &c.)

The former is immutable (and thus safe) and the latter cannot be turned back into an `AnyMap` after potentially illegal mutation (and is thus safe). It exposes the internals and would require `TypeIdState` being public, so an alternative would be to create another type which wraps the `HashMap`, like `AnyMap`, but with a TypeId-based API. This is perhaps a “purer” abstraction, but is a little more work.

I think I prefer using a different type for the raw access to adding a second set of methods everywhere.

What say you?

**Comment by palodequeso** [comment]
I think that your reasoning for not adding a pile of extra functions is sound. The API as it stands now is very clean, and will work for the majority of cases. As far as the proposed APIs, they would both work fine for my personal projects, but they may not cover everyone's cases. I will say, that it certainly seems like the safer approach and a good way to satisfy the majority of people trying to use the library in the same way as myself.

Between the two methods that you proposed, I definitely preferred the as_raw. It's a simple way to get access to the parts I would need without sacrificing any speed by making copies.

Finally, you mention a "purer" abstraction, and although the `as_raw` method proposed would cover what I need to do, the abstraction would definitely be the best fit, although I recognize it is a lot more work.

These are just my opinions, but I do feel that you probably have a better grasp on the language so definitely make sure to go with your own gut.

Also, thanks for writing this sweet library!

**Comment by chris-morgan** [comment]
How does 143ee062680311ca9c2ed5b7089bb0d741bc17c0 look, @palodequeso? It evolved a little further as I started writing it and the idea of producing two stacked rather than parallel layers popped into my head. I think it’s panned out quite nicely.

**Comment by palodequeso** [comment]
Looks like it will work quite nicely!

**Comment by palodequeso** [comment]
Did this ever make it in?

**Comment by chris-morgan** [comment]
This has landed in anymap v0.11.0 in the `raw` module.
