### ISSUE TITLE
concurrent feature

### ISSUE THREAD

**Issue by blaenk** [chris-morgan/anymap#19]
Just for the record, since we already discussed this a bit.

It would be nice if we created a `concurrent` feature that would basically add the `Sync + Send` bounds where necessary. I already do something similar in my [minor fork](https://github.com/blaenk/anymap/compare/master...blaenk:clone) and found that it's a very straightforward change compared to making it clonable.

Personally I really need this so that I could put stuff in an `Arc` and send it to a thread pool, but I understand if it's more of a hassle than it's worth here.

Specifically I need it to be both clonable _and_ concurrent. What I was discussing on IRC was that I don't know if it'd be possible to have to independent _yet composable_ features for each thing: `clone` and `concurrent`, given the fact (?) that the `with_clone` stuff would need to have the `Sync + Send` bounds added.

**Comment by blaenk** [comment]
To attempt to make the potential problem clearer, I'm thinking that something like this would be needed:

``` rust
#[cfg(not(feature = "clone"))]
pub use std::any::Any;
#[cfg(feature = "clone")]
pub use with_clone::Any;
#[cfg(feature = "concurrent")]
pub use with_concurrent::Any;
#[cfg(all(feature = "concurrent", feature = "clone"))]
pub use with_clone_and_concurrent::Any;
```

I imagine that `with_concurrent` might look something like this:

``` rust
use std::fmt;

#[doc(hidden)]
/// Pretty much just `std::any::Any + Sync + Send`.
pub trait Any: ::std::any::Any + Sync + Send { }

impl<T: 'static + Sync + Send> Any for T { }

impl<'a> fmt::Debug for &'a Any {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.pad("&Any")
    }
}

impl<'a> fmt::Debug for Box<Any> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.pad("Box<Any>")
    }
}
```

And `with_clone_and_concurrent` might look like this:

``` rust
use std::fmt;

#[doc(hidden)]
pub trait CloneToAny {
    /// Clone `self` into a new `Box<Any>` object.
    fn clone_to_any(&self) -> Box<Any>;
}

impl<T: 'static + Clone> CloneToAny for T {
    fn clone_to_any(&self) -> Box<Any> {
        Box::new(self.clone())
    }
}

#[doc(hidden)]
/// Pretty much just `std::any::Any + Clone`.
pub trait Any: ::std::any::Any + CloneToAny + Sync + Send { }

impl<T: 'static + Clone + Sync + Send> Any for T { }

impl Clone for Box<Any> {
    fn clone(&self) -> Box<Any> {
        (**self).clone_to_any()
    }
}

impl<'a> fmt::Debug for &'a Any {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.pad("&Any")
    }
}

impl<'a> fmt::Debug for Box<Any> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.pad("Box<Any>")
    }
}
```

That is, I don't know if we can have the two features be independent _but composable_ so that a `with_clone_and_concurrent::Any` wouldn't be necessary. Any ideas?

**Comment by chris-morgan** [comment]
anymap v0.11.0 includes the changes of #22 which superseded this approach and satisfied the features requested here.
