### ISSUE TITLE
use stable api

### ISSUE THREAD

**Issue by blaenk** [chris-morgan/anymap#21]
We should work towards getting this to build on the "stable" releases, e.g. beta. This means we have to remove our dependence on the `std_misc` and `core` features.

* `core` seems to be needed for `std::raw::TraitObject` which is needed for downcasting functionality.
* `std_misc` seems to be needed for `std::collections::hash_state::HashState` and `Drain`

Perhaps it might be worth a look at @reem's [typemap](https://github.com/reem/rust-typemap/blob/master/src/lib.rs) which doesn't require any features. In the worst case, we can probably salvage those features behind some sort of `"nightly"` feature, or better yet each one of those features under a separate feature, like `"downcast"` and `"drain"`.

**Comment by reem** [comment]
You should be able to use the traitobject crate to replace the use of `raw::TraitObject` in this package. The other unstable std stuff probably has to go behind a cargo feature. @blaenk if you want to make a PR, I'd be happy to review/merge.

**Comment by blaenk** [comment]
This should be covered by 569814ada323b0f4e75688eb5fb99fba25f2cc64 now

Thanks :)

**Comment by chris-morgan** [comment]
1851821 actually, and the published release v0.10.3.
