### ISSUE TITLE
Serialization support (`rustc-serialize`).

### ISSUE THREAD

**Issue by quadrupleslap** [chris-morgan/anymap#24]

**Comment by chris-morgan** [comment]
Step one: make a serializable `Any`. You’ll find that task hard enough, I think—I can’t think of a way to accomplish it in the language as it is at present; it’s going to need code generation, at the very least, to make it deserializable, without which I don’t think it’s worth doing.

**Comment by quadrupleslap** [comment]
Okay, but couldn't you accomplish this the same way you made CloneAny - with EncodableAny and DecodableAny markers and implement them for Encodable + Any and Decodable + Any respectively, and then implement Encodable for Map<EncodableAny> and Decodable for Map<DecodableAny>?
