### ISSUE TITLE
Internal storage as Box<Any> prevents passing references between tasks

### ISSUE THREAD

**Issue by tivek** [chris-morgan/anymap#7]
This is not a bug report, but a request for comments on a possibly new feature.

AnyMap internally stores data as boxed references to Any. Since Any does not carry Share and Send traits, the compiler does not allow access to the map from multiple tasks even though the original types of stored data should in principle allow it.

I have modified AnyMap by adding Send and Share bounds to Any and to type parameters of generic functions. The result is ConcurrentAnyMap, tivek/anymap@63f992fd6f758ff17790f3eda213a5594b95a76d. It is safely accessible from more than just the creating task through immutable references, which makes it useful as a centralized, immutable data store. std::sync::Arc so far seems to be happy.

At this point I do not like the code duplication between AnyMap and ConcurrentAnyMap. Share+Send need to be added at several places, which is pretty intrusive. To me it seems deriving would not work (but, I have just started with Rust and maybe I'm missing something obvious).

Hope someone finds it useful, and I'd appreciate your comments.

**Comment by chris-morgan** [comment]
I believe anymap v0.11.0 with the inclusion of the concurrency stuff from #22 deals with this. It’s still got to be `'static` for `Any`ness, of course, but it allows you to have a `Share` and `Send` map.
